-- src/migrations/008_create_orders.sql
--
-- The order header (F-07). One row per checkout.
--
-- Until now the bag lived only in the shopper's browser and the finished
-- order was handed to WhatsApp as text. This is the table that ends
-- that: an order placed on the site becomes a row here, and the shop
-- reads it from the admin panel instead of from a chat thread.
--
-- Two ideas drive the shape of this table.
--
-- 1. An order is a snapshot, not a set of pointers.
--
--    The contact details and the shipping address are copied onto the
--    row rather than read from `customers` at display time. A customer
--    who moves house must not retroactively change where last month's
--    parcel was sent — the address on an order is a record of what was
--    agreed, and joining to the live row would quietly rewrite history.
--    The same reasoning puts prices on order_items.
--
-- 2. A shopper does not need an account.
--
--    `customer_id` is nullable on purpose. The storefront bag says "You
--    can order without an account", and the sign-in offer there is about
--    keeping a wishlist across devices, not about buying. A guest order
--    carries its contact snapshot and nothing else; a signed-in order
--    carries the same snapshot plus the id, which is what lets the
--    account page list "my orders".
--
-- Status is split in two — `status` is where the parcel is, and
-- `payment_status` is whether the money arrived. They move
-- independently: an order can be paid and not yet packed, or cancelled
-- after payment and awaiting a refund. Collapsing them into one column
-- makes "paid but cancelled" unrepresentable, which is exactly the state
-- a refund lives in.

-- ============================================================
-- ORDER NUMBER SEQUENCE
-- ============================================================
--
-- The id is a UUID, which is right for a foreign key and useless to a
-- human. Nobody reads a UUID down the phone. `order_number` is the
-- handle the shop and the shopper actually use — "SB-001042".
--
-- Generated by the database rather than the application, so two
-- checkouts landing in the same millisecond cannot be handed the same
-- number. Starts above 1000 so the first order does not advertise
-- itself as the first order.

CREATE SEQUENCE IF NOT EXISTS orders_number_seq START WITH 1001 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS orders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  order_number VARCHAR(24) NOT NULL
    DEFAULT ('SB-' || LPAD(nextval('orders_number_seq')::TEXT, 6, '0')),

  -- NULL for a guest checkout. ON DELETE SET NULL rather than CASCADE:
  -- deleting a customer must never delete the record of what they
  -- bought — the shop still shipped it and still has the money.
  --
  -- Customers are soft-deleted anyway (see customer.routes.js), so this
  -- is the second line, not the first.
  customer_id UUID NULL,

  -- ----------------------------------------------------------
  -- CONTACT SNAPSHOT
  -- ----------------------------------------------------------
  --
  -- Who to call about this parcel, as given at checkout. Always
  -- present, account or not.

  contact_name VARCHAR(255) NOT NULL,

  contact_email VARCHAR(255) NOT NULL,

  contact_phone VARCHAR(20) NOT NULL,

  -- ----------------------------------------------------------
  -- SHIPPING ADDRESS SNAPSHOT
  -- ----------------------------------------------------------
  --
  -- Flat columns rather than a JSONB blob. The shop searches by city
  -- and pincode when a courier asks, and an index over a JSONB path to
  -- do that is work bought for no benefit — this address shape is not
  -- going to grow.

  shipping_line1 VARCHAR(255) NOT NULL,

  shipping_line2 VARCHAR(255) NULL,

  shipping_landmark VARCHAR(255) NULL,

  shipping_city VARCHAR(120) NOT NULL,

  shipping_state VARCHAR(120) NOT NULL,

  -- Indian PIN codes are six digits. Kept as text, not an integer: a
  -- pincode is an identifier, never something to do arithmetic on, and
  -- an integer would eat a leading zero.
  shipping_postal_code VARCHAR(12) NOT NULL,

  shipping_country VARCHAR(80) NOT NULL DEFAULT 'India',

  -- ----------------------------------------------------------
  -- STATUS
  -- ----------------------------------------------------------

  status VARCHAR(32) NOT NULL DEFAULT 'pending_payment',

  payment_status VARCHAR(32) NOT NULL DEFAULT 'pending',

  -- ----------------------------------------------------------
  -- MONEY
  -- ----------------------------------------------------------
  --
  -- DECIMAL, matching products.base_price — never a float. Rupees at
  -- two places cannot be represented exactly in binary floating point,
  -- and a total that is off by a paisa is a total the shop cannot
  -- reconcile against the gateway.
  --
  -- `total` is stored rather than computed on read. It is what the
  -- shopper agreed to pay; recomputing it later from lines and a
  -- shipping rule would let a change to that rule silently restate an
  -- old order.

  subtotal DECIMAL(10,2) NOT NULL
    CHECK (subtotal >= 0),

  -- Free all over India today, which is what the storefront promises.
  -- A column rather than a constant so the promise can change without
  -- rewriting what past orders were charged.
  shipping_fee DECIMAL(10,2) NOT NULL DEFAULT 0
    CHECK (shipping_fee >= 0),

  total DECIMAL(10,2) NOT NULL
    CHECK (total >= 0),

  currency CHAR(3) NOT NULL DEFAULT 'INR',

  -- ----------------------------------------------------------
  -- NOTES
  -- ----------------------------------------------------------

  -- "Please deliver after 6pm" — the shopper's own words.
  customer_note TEXT NULL,

  -- The shop's internal note. Never shown on the storefront.
  admin_note TEXT NULL,

  cancellation_reason TEXT NULL,

  -- ----------------------------------------------------------
  -- LIFECYCLE TIMESTAMPS
  -- ----------------------------------------------------------
  --
  -- One column per transition rather than a single `status_changed_at`.
  -- "How long between paid and shipped?" is the question the shop will
  -- actually ask, and a single column cannot answer it.

  placed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  paid_at TIMESTAMPTZ NULL,

  packed_at TIMESTAMPTZ NULL,

  shipped_at TIMESTAMPTZ NULL,

  delivered_at TIMESTAMPTZ NULL,

  cancelled_at TIMESTAMPTZ NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT uq_orders_order_number
    UNIQUE (order_number),

  CONSTRAINT fk_orders_customer
    FOREIGN KEY (customer_id)
    REFERENCES customers(id)
    ON UPDATE CASCADE
    ON DELETE SET NULL,

  -- The list of statuses is duplicated in src/config/order.policy.js.
  -- That module is where the transitions between them are decided; this
  -- constraint only stops a value nobody defined from reaching the
  -- table, whether it came through the service or through psql.
  CONSTRAINT orders_status_check
    CHECK (status IN (
      'pending_payment',
      'confirmed',
      'packed',
      'shipped',
      'delivered',
      'cancelled'
    )),

  CONSTRAINT orders_payment_status_check
    CHECK (payment_status IN (
      'pending',
      'paid',
      'failed',
      'refunded'
    )),

  -- The one arithmetic invariant worth enforcing in the database: a
  -- total that does not equal its parts is corruption, not a business
  -- state, and no application bug should be able to write one.
  --
  -- Not named `orders_total_check`: Postgres auto-names the inline
  -- `CHECK (total >= 0)` on the column above exactly that, and the two
  -- would collide.
  CONSTRAINT orders_total_sums_check
    CHECK (total = subtotal + shipping_fee)
);

-- ============================================================
-- INDEXES
-- ============================================================

-- "My orders", newest first — the account page's only query.
CREATE INDEX IF NOT EXISTS idx_orders_customer_placed
  ON orders (customer_id, placed_at DESC);

-- The admin queue, which opens on "what has been paid and not yet
-- shipped". Status first because that is what is filtered; placed_at
-- second because within a status the oldest order is the most urgent.
CREATE INDEX IF NOT EXISTS idx_orders_status_placed
  ON orders (status, placed_at DESC);

CREATE INDEX IF NOT EXISTS idx_orders_payment_status
  ON orders (payment_status);

CREATE INDEX IF NOT EXISTS idx_orders_placed_at
  ON orders (placed_at DESC);

-- Looking an order up from a number read down the phone. Case-folded,
-- because it will be typed in as "sb-001042" at least as often.
CREATE INDEX IF NOT EXISTS idx_orders_order_number_lower
  ON orders (LOWER(order_number));

-- Finding a guest's orders, who have no customer_id to search by.
CREATE INDEX IF NOT EXISTS idx_orders_contact_email
  ON orders (LOWER(contact_email));
